platform :ios, '8.0'

pod 'TTTAttributedLabel'
use_frameworks!
pod 'JSONModel'
pod 'TSMessages', :git => 'https://github.com/KrauseFx/TSMessages.git'
pod 'IQKeyboardManager', '~> 4.0.0'
pod 'SDWebImage'
pod 'CLLocationManager-blocks'
pod 'HMSegmentedControl'
pod 'ActionSheetPicker-3.0', '~> 1.7.1'
pod 'BOString'
#pod 'MGSwipeTableCell'
pod 'SVPullToRefresh'
pod 'UITextView+Placeholder'
pod 'A3ParallaxScrollView', '~> 1.0'
pod 'STPopup'
pod 'APParallaxHeader'
pod 'MZAppearance'
pod 'MGInstagram'
pod 'InstagramKit', '~> 3.0'
pod 'Fabric'
pod 'Crashlytics'
pod 'NSDate-Time-Ago'
pod 'NSDate+Calendar'
pod 'MMPickerView', '~> 0.0.1'
pod 'IDMPhotoBrowser'
pod 'YLGIFImage'
pod 'AFNetworking', '~> 3.0'
pod 'AMPopTip'
pod 'Parse'

#facebook SDK
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'

pod 'SSKeychain'
#================ Possible can be deleted =====================#
#pod 'DBCamera', '~> 2.4'
pod 'PureLayout'

#pod 'Masonry'
#pod 'Realm'
#pod 'SKSplashView'

#pod 'iCarousel'
#================ debugging =====================#
#pod 'CocoaLumberjack'

#pod 'Canvas', '~> 0.1.2'
#pod 'ADTransitionController'
#pod 'pop', '~> 1.0'
#pod 'GoogleMaps'
#pod 'LPGoogleFunctions'
